swagger: "2.0"
info:
  description: "This is the documentation of the backend codebase I developed for the 3rd deliverable of a 3 part exercice for the course of Databases. This course is part of the Electrical Engineering and Computer Engineering undergraduate program at Aristotle University of Thessaloniki."
  version: "1.0.0"
  title: "HouseAPI"
  contact:
    email: "georgekam96@gmail.com"
host: "83.212.115.201:5000"
basePath: "/api"
schemes:
- "http"
paths:
  /User:
    get:
      summary: "Returns every user"
      description: "It returns every user registered in HouseDB"
      produces: 
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
              $ref: "#/definitions/UserResponse"
        500:
          description: "Unexpected error"
definitions:
  UserResponse:
    type: "object"
    properties:
      status:
        type: "string"
      data:
        type: "array"
        items:
          type: "object"
          properties:
            id:
              type: "integer"
              format: "int64"
            name:
              type: "string"
            contact_email:
              type: "string"
            contact_number:
              type: "string"
externalDocs:
  description: "Find out more about HouseAPI"
  url: "https://github.com/gkamtzir/HouseApi"